config/routes.rb
Rails.application.routes.draw do
  root                 "static_pages#home"

  get     "help"    => "static_pages#help"
  get     "about"   => "static_pages#about"
  get     "contact" => "static_pages#contact"
  get     "signup"  => "users#new"
  get     "login"   => "sessions#new"
  post    "login"   => "sessions#create"
  delete  "logout"  => "sessions#destroy"

  get "/users/:user_id/events/:id/invite", to: "events#invite", as: "invite"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"
  get "users/:id/change_passwrod", to: "users#change_password", as: "change_password"
  
  resources :users do
    resources :events
    resources :account_activations, only: [:new, :create]
  end

  resources :events do
    resources :guests
  end

  resources :account_activations, only: :edit
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :event

  validates :name, presence: true, length: { maximum: 140 }
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
  before_action :redirect_if_incorrect_user, only: [:edit, :update, :destroy]
  before_action :set_user_event_and_guest, only: [:new, :create, :edit, :update, :destroy]

  def new
    @guest = @event.guests.build
  end

  def create
    @guest = @event.guests.build(guest_params)
    if @guest.save
      flash[:success] = "Thanks for adding your info!"
      if user_owns_event?        
        redirect_to user_event_path(@event, user_id: @user) 
      else
        redirect_to root_url
      end
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @guest.update(guest_params)
      flash[:success] = "Guest successfully updated"
      redirect_to user_event_path(@event, user_id: @user)
    else
      render "edit"
    end
  end

  def destroy
    @guest.destroy
    flash[:success] = "Guest successfully removed"
    redirect_to user_event_path(@event, user_id: @user)
  end

  private

    def guest_params
      params.require(:guest).permit(:name, :responsibility, :event_id)
    end

    def set_user_event_and_guest
      @event = Event.find(params[:event_id])
      @user = @event.user
      @guest = @event.guests.find_by(id: params[:id])
    end

    def user_owns_event?
      logged_in? && @event.user_id == current_user.id
    end

    def identify_user_in_params
      Event.find_by(id: params[:event_id]).user
    end
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/views/guests/_guest.html.erb
<div class="col-xs-4">
  <p class="h5">
    Name: 
  </p>
  <p class="h5">
    Responsibility: 
  </p>
</div>

<div class="col-xs-4">
  <p class="h5">
  <%= guest.name %>
  </p>
  <p class="h5">
  <% if !guest.responsibility.blank? %>
      <%= guest.responsibility %>
  <% else %>
      No responsibility claimed
  <% end %>
  </p>
</div>

<div class="col-xs-4">
    <%= link_to "Edit This Guest", edit_event_guest_path(guest, event_id: guest.event), class: "btn btn-default" %>
    <%= link_to "Delete This Guest", event_guest_path(guest.event.user, event_id: guest.event), 
        method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
</div>

<br>
<br>
<br>
<br>

app/views/guests/edit.html.erb
<% provide(:title, "Edit Guest") %>
<h1>Edit Guest</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@event, @guest]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :responsibility %>
      <%= f.text_field :responsibility, class: "form-control" %>
      
      <%= f.submit "Update Guest", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/guests/new.html.erb
<% provide(:title, "Add A Guest") %>

<h1>New Guest for <%= @event.title %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@event, @guest]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter your name..." %>

      <%= f.label :responsibility %>
      <%= f.text_area :responsibility, class: "form-control", placeholder: "What you're bringing/what you'll handle..." %>

      <%= f.submit "Add Me!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>