config/routes.rb
Rails.application.routes.draw do
  root                 "static_pages#home"

  get     "help"    => "static_pages#help"
  get     "about"   => "static_pages#about"
  get     "contact" => "static_pages#contact"
  get     "signup"  => "users#new"
  get     "login"   => "sessions#new"
  post    "login"   => "sessions#create"
  delete  "logout"  => "sessions#destroy"

  get "/users/:user_id/events/:id/invite", to: "events#invite", as: "invite"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"
  get "users/:id/change_passwrod", to: "users#change_password", as: "change_password"
  
  resources :users do
    resources :events
    resources :account_activations, only: [:new, :create]
  end

  resources :events do
    resources :guests
  end

  resources :account_activations, only: :edit
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, dependent: :destroy
  has_many :guests, through: :events

  attr_accessor :remember_token, :activation_token

  before_save :downcase_email 

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true

  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_activation_digest
    self.activation_token = User.new_token
    update_attribute(:activation_digest, User.digest(activation_token))
  end
  
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  private

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
  skip_before_action :redirect_if_incorrect_user, only: [:new, :create]
  before_action :set_user, only: [:dashboard, :show, :edit, :change_password, :update]

  def dashboard
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the RSVP App!"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def change_password
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def identify_user_in_params
      User.find_by(id: params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password.html.erb
<% provide(:title, "Change Password") %>

<h1>Change Password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/dashboard.html.erb
<% provide(:title, "Dashboard") %>

<h1>Dashboard</h1>

<div class="center">
  <%= link_to "New Event", new_user_event_path(@user), class: "btn btn-lg btn-primary", "data-no-turbolink" => true %>
  <% unless @user.activated? %>
    <%= link_to "Activate Account", new_user_account_activation_path(user_id: @user), class: "btn btn-lg btn-primary" %>
  <% end %>
  <%= link_to "View Profile", user_path(@user), class: "btn btn-lg btn-primary" %>
  <%= link_to "Edit Profile", edit_user_path, class: "btn btn-lg btn-primary" %>
</div>

<% if @user.events.any? %>
  <div class="row">
    <h3>Events</h3>
    <div class="col-md-8">
      <%= render @user.events %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<h1>Update Your Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<h1>Sign Up</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %> 
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, "Confirmation" %> 
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %> 
      <% end %>
      <p>Already signed up? <%= link_to "Log in", login_path %></p> 
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<h1>Your Profile</h1>

<h4>Name: <%= @user.name %></h4>
<h4>Email: <%= @user.email %><h4>

<%= link_to "Edit", edit_user_path, class: "btn btn-primary" %>