config/routes.rb
Rails.application.routes.draw do
  root                 "static_pages#home"

  get     "help"    => "static_pages#help"
  get     "about"   => "static_pages#about"
  get     "contact" => "static_pages#contact"
  get     "signup"  => "users#new"
  get     "login"   => "sessions#new"
  post    "login"   => "sessions#create"
  delete  "logout"  => "sessions#destroy"

  get "/users/:user_id/events/:id/invite", to: "events#invite", as: "invite"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"
  get "users/:id/change_passwrod", to: "users#change_password", as: "change_password"
  
  resources :users do
    resources :events
    resources :account_activations, only: [:new, :create]
  end

  resources :events do
    resources :guests
  end

  resources :account_activations, only: :edit
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :guests, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { maximum: 100 }
  validates :location, presence: true, length: { maximum: 255 }
  validates :date, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :invite]

  def index
    @events = current_user.events
  end

  def show
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event successfully created!"
      redirect_to current_user
    else
      render "new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event updated!"
      redirect_to current_user
    else
      render "edit"
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event successfully deleted"
    redirect_to current_user
  end

  def invite
    @user = current_user
  end

  private

    def set_event
      @event = current_user.events.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date, :time, :location)
    end

    def identify_user_in_params
      User.find_by(id: params[:user_id])
    end

    # params[:event][:date] regex: /\A201\d-[0|1]\d-[0-3]\d [0|1]\d:[0-6]\d [a|p]m\z/i 
    # for validating valid date with javascript disabled
    # can't validate in model since .build and .update convert it to a datetime
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<li>
  <h3><%= event.title %></h3>
  <h4>Date: <%= event.date.strftime("%A %B %-d, %Y at %-l:%M %P") %></h4>
  <h4>Location: <%= event.location %></h4>
  <h4>Registered Guests: <%= event.guests.count %></h4>

  <%= link_to "Invite Guests", invite_path(event, user_id: event.user_id), class: "btn btn-default" %>
  <%= link_to "View Event", user_event_path(event, user_id: event.user_id), class: "btn btn-default" %>
  <%= link_to "Edit Event", edit_user_event_path(event, user_id: event.user), class: "btn btn-default", "data-no-turbolink" => true %>
  <%= link_to "Delete Event", user_event_path(event, user_id: event.user), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
</li>

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "location_search.js" %>
  <%= javascript_include_tag "datetime_select.js" %>
<% end %>

<h1>Edit Your Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@user, @event]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :date %>
      <%= f.text_field :date, id: "datetimepicker1",
          class: "form-control" %>

      <%= f.label :location %>
      <%= f.text_field :location, id: "locationSearchField",
          class: "form-control" %>

      <%= f.submit "Update my event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, "My Events") %>

<h1>My Events</h1>

<ul>
  <%= render @events %>
</ul>

app/views/events/invite.html.erb
<h1>Invite Guests</h1>

<h3>
  To invite your guests, send them a link to 
  <%= link_to "#{new_event_guest_url(event_id: @event)}", 
      new_event_guest_path(event_id: @event) %>.
</h3>
<h3>
  Once they complete the form, we'll update their info on 
  <%= link_to "your #{@event.title} event homepage", user_event_path(@event, user_id: @user) %>.
</h3>

<p>
  We hope to offer email invites soon.
</p>

app/views/events/new.html.erb
<%= provide(:title, "New Event") %>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "location_search.js" %>
  <%= javascript_include_tag "datetime_select.js" %>
<% end %>

<h1>Create an Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:user, @event]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label "Event Name" %>
      <%= f.text_field :title, class: "form-control", 
          placeholder: "Name your event" %>

      <%= f.label "Event Date/Time" %>
      <%= f.text_field :date, id: "datetimepicker1",
          class: "form-control" %>

      <%= f.label "Event Location" %>
      <%= f.text_field :location, id: "locationSearchField", 
          class: "form-control" %>

      <%= f.submit "Create my event!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<div class="center">
  <%= link_to "My Dashboard", user_path(@event.user), class: "btn btn-lg btn-primary" %>
  <%= link_to "Invite Guests", invite_path(@event, user_id: @event.user_id), class: "btn btn-lg btn-primary" %>
  <%= link_to "Edit Event", edit_user_event_path(@event, user_id: @event.user), class: "btn btn-lg btn-primary", "data-no-turbolink" => true %>
  <%= link_to "Delete Event", user_event_path(@event, user_id: @event.user), method: :delete, class: "btn btn-lg btn-primary", data: { confirm: "Are you sure?" } %>
</div>

<div class="row">
  <div class="col-md-8">
    <h3>Date:</h3> 
    <%= @event.date.strftime("%A %B %-d, %Y at %-l:%M %P") %>
    <h3>Location:</h3> 
      <address>
        <%= @event.location %>
      </address>
    <h3>Guests
    <% if @event.guests.count > 0 %>
      <%= "(#{@event.guests.count})" %></h3>
    <% else %>
      </h3>
      <div class="col-md-4 h6">
        Nobody has RSVP'd :(
      </div>
    <% end %>
  </div>
</div>

<%= render @event.guests %>

<br>

<div class="col-md-6">
  <%= link_to "Add a guest", new_event_guest_path(event_id: @event), class: "btn btn-success" %>
</div>