config/routes.rb
Rails.application.routes.draw do
  root                 "static_pages#home"

  get     "help"    => "static_pages#help"
  get     "about"   => "static_pages#about"
  get     "contact" => "static_pages#contact"
  get     "signup"  => "users#new"
  get     "login"   => "sessions#new"
  post    "login"   => "sessions#create"
  delete  "logout"  => "sessions#destroy"

  get "/users/:user_id/events/:id/invite", to: "events#invite", as: "invite"

  get "users/:id/dashboard", to: "users#dashboard", as: "dashboard"
  get "users/:id/change_passwrod", to: "users#change_password", as: "change_password"
  
  resources :users do
    resources :events
    resources :account_activations, only: [:new, :create]
  end

  resources :events do
    resources :guests
  end

  resources :account_activations, only: :edit
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The RSVP App
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul> 
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "RSVP App", root_path, id: "logo" %> 
    <nav>
      <ul class="nav navbar-nav navbar-right"> 
        <li><%= link_to "About", about_path %></li> 
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path(current_user) %></li>
              <li><%= link_to "View Profile", current_user %></li> 
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Change Password", change_password_path(current_user) %></li>
            </ul> 
          </li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li> 
          <li><%= link_to "Log in", login_path %></li>
        <% end %> 
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'letters.png' %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
    <%= yield :javascript_includes %>
    <%= csrf_meta_tags %> 
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%= msg_type %>"><%= msg %></div> 
      <% end %>
      <%= yield %> 
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>